### ISSUE TITLE
关于直连功能的奇怪问题

### ISSUE THREAD

**Issue by fantastlcok** [slurin/BaiduPanAutoReshare#2]
在部署完后，我导入以前的NijiharaTsubasa 版的数据。
以前的旧版数据分享链接 可以显示直连下载，而我使用这个版本生成的链接 没有直接功能。

**Comment by slurin** [comment]
很惭愧，我没有安装过原版，甚至连我修改的也只是在本地环境上运行了一下。根据上述的情景并不能完全确定故障原因。

但是我估计造成此现象的原因是在数据库导入过程中导致的：
这个程序在修改的过程中相比原版在数据库上使用了外键，因此原来的数据库导入可能会失败。其中users表增加了siteu_id与ID@siteusers对应，因此直接导入是不行的。watchlist也有新增的项siteu_id，并且user_id与原来的对比有了外键约束。
建议您先参考install.php中创建数据库表的部分，修改导出的sql文本之后再导入。

**Comment by fantastlcok** [comment]
@slurin 刚开始也发现了这个问题，不过成功导入了。
原来导致这个问题，不是您的原因。
当分享的文件是文件夹时是没有直连功能的，我看漏了。以前是直接分享的文件。
