### ISSUE TITLE
安装成功后仍然跳转到install.php页面的第一步，无限循环咋办？

### ISSUE THREAD

**Issue by laputaer** [slurin/BaiduPanAutoReshare#3]
如题，到最后一步显示已经安装成功，但打开其他页面还是会跳转到install.php页面的第一步，无限循环额，求解！
PHP配置文件显示如下 ，不知道是不是这个的原因？如果是的话，不知道怎么关闭呢，不太懂。谢谢大大。
`open_basedir => no value => no value`

**Comment by laputaer** [comment]
找到原因了，因为文件夹没有写权限，没法自动创建config.php文件

**Comment by slurin** [comment]
此项目已废除，不建议继续使用。
